export const defaultGraph = {
	last_node_id: 9,
	last_link_id: 9,
	nodes: [
		{
			id: 7,
			type: "提示词_Zho",
			pos: [413, 389],
			size: { 0: 425.27801513671875, 1: 180.6060791015625 },
			flags: {},
			order: 3,
			mode: 0,
			inputs: [{ name: "CLIP模型", type: "CLIP", link: 5 }],
			outputs: [{ name: "条件", type: "CONDITIONING", links: [6], slot_index: 0 }],
			properties: {},
			widgets_values: ["low quality"],
		},
		{
			id: 6,
			type: "提示词_Zho",
			pos: [415, 186],
			size: { 0: 422.84503173828125, 1: 164.31304931640625 },
			flags: {},
			order: 2,
			mode: 0,
			inputs: [{ name: "CLIP模型", type: "CLIP", link: 3 }],
			outputs: [{ name: "条件", type: "CONDITIONING", links: [4], slot_index: 0 }],
			properties: {},
			widgets_values: ["cat"],
		},
		{
			id: 5,
			type: "初始潜空间_Zho",
			pos: [473, 609],
			size: { 0: 315, 1: 106 },
			flags: {},
			order: 1,
			mode: 0,
			outputs: [{ name: "潜空间", type: "LATENT", links: [2], slot_index: 0 }],
			properties: {},
			widgets_values: [512, 512, 1],
		},
		{
			id: 3,
			type: "采样器_Zho",
			pos: [863, 186],
			size: { 0: 315, 1: 262 },
			flags: {},
			order: 4,
			mode: 0,
			inputs: [
				{ name: "模型", type: "MODEL", link: 1 },
				{ name: "正向提示词", type: "CONDITIONING", link: 4 },
				{ name: "负向提示词", type: "CONDITIONING", link: 6 },
				{ name: "潜空间图像", type: "LATENT", link: 2 },
			],
			outputs: [{ name: "潜空间图像", type: "LATENT", links: [7], slot_index: 0 }],
			properties: {},
			widgets_values: [156680208700286, 20, 8, "euler", "normal", 1],
		},
		{
			id: 8,
			type: "VAE解码器_Zho",
			pos: [1209, 188],
			size: { 0: 210, 1: 46 },
			flags: {},
			order: 5,
			mode: 0,
			inputs: [
				{ name: "samples", type: "LATENT", link: 7 },
				{ name: "VAE模型", type: "VAE", link: 8 },
			],
			outputs: [{ name: "图像", type: "IMAGE", links: [9], slot_index: 0 }],
			properties: {},
		},
		{
			id: 9,
			type: "图像保存_Zho",
			pos: [1451, 189],
			size: { 0: 210, 1: 26 },
			flags: {},
			order: 6,
			mode: 0,
			inputs: [{ name: "图像", type: "IMAGE", link: 9 }],
			properties: {},
		},
		{
			id: 4,
			type: "主模型加载器_Zho",
			pos: [26, 474],
			size: { 0: 315, 1: 98 },
			flags: {},
			order: 0,
			mode: 0,
			outputs: [
				{ name: "主模型", type: "MODEL", links: [1], slot_index: 0 },
				{ name: "CLIP模型", type: "CLIP", links: [3, 5], slot_index: 1 },
				{ name: "VAE模型", type: "VAE", links: [8], slot_index: 2 },
			],
			properties: {},
			widgets_values: ["v1-5-pruned-emaonly.ckpt"],
		},
	],
	links: [
		[1, 4, 0, 3, 0, "MODEL"],
		[2, 5, 0, 3, 3, "LATENT"],
		[3, 4, 1, 6, 0, "CLIP"],
		[4, 6, 0, 3, 1, "CONDITIONING"],
		[5, 4, 1, 7, 0, "CLIP"],
		[6, 7, 0, 3, 2, "CONDITIONING"],
		[7, 3, 0, 8, 0, "LATENT"],
		[8, 4, 2, 8, 1, "VAE"],
		[9, 8, 0, 9, 0, "IMAGE"],
	],
	groups: [],
	config: {},
	extra: {},
	version: 0.4,
};
